name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: fix ownership
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        sudo apt-get install --assume-yes p7zip-full

    - name: ls
      run: |
        ls -R

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Compile project
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Pack project for release
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
      run: |
        zip -j SC2_Unpacker.zip CHANGELOG README.md build/SC2_Unpacker.exe

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ matrix.toolchain }}
        path: |
            build/SC2_Unpacker.exe

    - name: Create prerelease
      if: github.ref == 'refs/heads/main'
      uses: mathieucarbou/marvinpinto-action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "latest"
        title: "SoulCalibur II unpacker"
        files: |
            SC2_Unpacker.zip

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: mathieucarbou/marvinpinto-action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: "${{ contains(github.ref, '-rc') }}"
        title: "SoulCalibur II unpacker"
        files: |
            SC2_Unpacker.zip